-- ================================================
-- Seed: Produits de démonstration pour les 3 catégories
-- cosmetique_fr, parfum_fr, aromes_fr
-- + données de performance/stabilité pour les parfums
-- ================================================

-- ================================================
-- COSMÉTIQUES (15 produits)
-- ================================================
INSERT INTO public.cosmetique_fr (code, nom_commercial, inci, cas_no, gamme, origine, description, benefices, benefices_aqueux, benefices_huileux, application, solubilite, aspect, certifications, type_de_peau, partie_utilisee, statut, food_grade) VALUES
('COS-001', 'Rose Damascena Extract', 'Rosa Damascena Flower Extract', '90106-38-0', 'Botanicals Premium', 'Bulgarie', 'Extrait de rose de Damas obtenu par distillation à la vapeur. Riche en composés bioactifs aux propriétés apaisantes et régénérantes exceptionnelles.', 'Anti-âge, Apaisant, Régénérant', 'Hydratant, Tonifiant', 'Nourrissant, Émollient', 'Soins visage, Sérums, Crèmes anti-âge', 'Hydrosoluble', 'Liquide limpide rosé', 'COSMOS, ECOCERT, ISO 16128', 'Tous types de peau', 'Fleur', 'ACTIF', 'Non'),
('COS-002', 'Acide Hyaluronique Complex', 'Sodium Hyaluronate', '9067-32-7', 'Active Ingredients', 'France', 'Complexe d''acide hyaluronique multi-poids moléculaire pour une hydratation profonde et durable à tous les niveaux de la peau.', 'Hydratation intense, Repulpant, Anti-rides', 'Hydratation profonde, Film protecteur', NULL, 'Sérums, Crèmes hydratantes, Masques', 'Hydrosoluble', 'Poudre blanche', 'COSMOS, Vegan', 'Tous types de peau', NULL, 'ACTIF', 'Non'),
('COS-003', 'Huile d''Argan Vierge Bio', 'Argania Spinosa Kernel Oil', '223747-87-1', 'Huiles Précieuses', 'Maroc', 'Huile d''argan première pression à froid, riche en vitamine E et acides gras essentiels. Nourrit et protège la peau en profondeur.', 'Nourrissant, Protecteur, Anti-oxydant', NULL, 'Assouplissant, Éclat', 'Soins visage, Corps, Cheveux', 'Liposoluble', 'Huile jaune dorée', 'COSMOS, BIO, Fair Trade', 'Peaux sèches et matures', 'Amande du fruit', 'ACTIF', 'Oui'),
('COS-004', 'Niacinamide Pure 99%', 'Niacinamide', '98-92-0', 'Active Ingredients', 'Suisse', 'Vitamine B3 de haute pureté. Régule le sébum, unifie le teint et renforce la barrière cutanée. Compatible avec la plupart des actifs.', 'Éclat du teint, Pores resserrés, Anti-taches', 'Régulateur sébum, Unifiant', NULL, 'Sérums, Crèmes, Lotions', 'Hydrosoluble', 'Poudre cristalline blanche', 'Pharma Grade, Vegan', 'Peaux mixtes à grasses', NULL, 'ACTIF', 'Non'),
('COS-005', 'Extrait de Centella Asiatica', 'Centella Asiatica Extract', '84696-21-9', 'Botanicals Premium', 'Madagascar', 'Extrait titré en asiaticoside, madécassoside et acide asiatique. Favorise la cicatrisation et apaise les peaux sensibles.', 'Cicatrisant, Apaisant, Raffermissant', 'Anti-inflammatoire, Réparateur', NULL, 'Soins anti-âge, Post-acte, Peaux sensibles', 'Hydrosoluble', 'Liquide brun clair', 'COSMOS, ISO 16128', 'Peaux sensibles et abîmées', 'Feuille', 'ACTIF', 'Non'),
('COS-006', 'Squalane Végétal', 'Squalane', '111-01-3', 'Émollients', 'Espagne', 'Squalane d''origine végétale (olive). Émollient léger et non comédogène qui restaure le film hydrolipidique de la peau.', 'Hydratant, Émollient, Protecteur', NULL, 'Non gras, Absorption rapide', 'Soins visage, Corps, Bébé', 'Liposoluble', 'Huile incolore transparente', 'COSMOS, Vegan, NATRUE', 'Tous types de peau', 'Olive', 'ACTIF', 'Oui'),
('COS-007', 'Bakuchiol Natural', 'Bakuchiol', '10309-37-2', 'Active Ingredients', 'Inde', 'Alternative naturelle au rétinol. Stimule la production de collagène sans irritation ni photosensibilisation.', 'Anti-âge, Anti-rides, Éclat', NULL, 'Lissant, Fermeté', 'Sérums anti-âge, Crèmes nuit', 'Liposoluble', 'Liquide violet foncé', 'COSMOS, Vegan', 'Peaux matures', 'Graine', 'ACTIF', 'Non'),
('COS-008', 'Beurre de Karité Brut Bio', 'Butyrospermum Parkii Butter', '68424-60-2', 'Beurres & Cires', 'Burkina Faso', 'Beurre de karité non raffiné, riche en insaponifiables. Nourrit intensément et protège les peaux les plus sèches.', 'Nourrissant intense, Protecteur, Réparateur', NULL, 'Émollient riche, Filmogène', 'Baumes, Crèmes corps, Lèvres', 'Liposoluble', 'Solide crème ivoire', 'COSMOS, BIO, Fair Trade, ECOCERT', 'Peaux sèches et très sèches', 'Noix', 'ACTIF', 'Oui'),
('COS-009', 'Vitamine C Stabilisée', 'Ascorbyl Glucoside', '129499-78-1', 'Active Ingredients', 'Japon', 'Forme stabilisée de vitamine C résistante à l''oxydation. Effet antioxydant puissant et éclaircissant progressif.', 'Antioxydant, Éclaircissant, Anti-taches', 'Éclat, Protection UV indirecte', NULL, 'Sérums, Crèmes jour, Soins éclat', 'Hydrosoluble', 'Poudre blanche', 'Pharma Grade', 'Tous types de peau', NULL, 'ACTIF', 'Non'),
('COS-010', 'Huile de Jojoba Bio', 'Simmondsia Chinensis Seed Oil', '61789-91-1', 'Huiles Précieuses', 'Argentine', 'Cire liquide dont la composition est très proche du sébum humain. Régule la production de sébum et nourrit sans graisser.', 'Régulateur, Nourrissant, Protecteur', NULL, 'Pénétrant, Non comédogène', 'Soins visage, Cheveux, Massage', 'Liposoluble', 'Huile jaune clair', 'COSMOS, BIO', 'Peaux mixtes à grasses', 'Graine', 'ACTIF', 'Non'),
('COS-011', 'Aloe Vera Gel Concentré 200x', 'Aloe Barbadensis Leaf Juice', '85507-69-3', 'Botanicals Premium', 'Mexique', 'Gel d''aloe vera concentré 200 fois, riche en polysaccharides. Hydrate, apaise et favorise la régénération cellulaire.', 'Hydratant, Apaisant, Réparateur', 'Adoucissant, Anti-rougeurs', NULL, 'Soins après-soleil, Gels, Masques', 'Hydrosoluble', 'Gel translucide', 'COSMOS, BIO, IASC Certified', 'Tous types de peau', 'Feuille', 'ACTIF', 'Oui'),
('COS-012', 'Acide Glycolique 70%', 'Glycolic Acid', '79-14-1', 'Active Ingredients', 'France', 'Acide alpha-hydroxylé (AHA) d''origine naturelle. Exfoliant chimique puissant qui stimule le renouvellement cellulaire.', 'Exfoliant, Éclat, Anti-taches', 'Lissant, Peeling doux', NULL, 'Peelings, Sérums, Crèmes nuit', 'Hydrosoluble', 'Liquide incolore', 'Pharma Grade', 'Peaux ternes et épaisses', NULL, 'ACTIF', 'Non'),
('COS-013', 'Huile de Nigelle Bio', 'Nigella Sativa Seed Oil', '68650-39-5', 'Huiles Précieuses', 'Égypte', 'Huile de cumin noir première pression à froid. Riche en thymoquinone, puissant anti-inflammatoire et antioxydant naturel.', 'Anti-inflammatoire, Purifiant, Antioxydant', NULL, 'Régulateur, Apaisant', 'Soins peaux à imperfections, Corps', 'Liposoluble', 'Huile ambrée foncée', 'COSMOS, BIO', 'Peaux à imperfections', 'Graine', 'ACTIF', 'Oui'),
('COS-014', 'Peptide Matrixyl 3000', 'Palmitoyl Tripeptide-1 (and) Palmitoyl Tetrapeptide-7', '147732-56-7', 'Active Ingredients', 'France', 'Complexe peptidique breveté qui stimule la synthèse de collagène et d''élastine pour un effet anti-rides visible.', 'Anti-rides, Fermeté, Élasticité', 'Repulpant, Lissant', NULL, 'Sérums anti-âge, Contour des yeux', 'Hydrosoluble', 'Liquide incolore', 'Patent Sederma', 'Peaux matures', NULL, 'ACTIF', 'Non'),
('COS-015', 'Eau de Bleuet Bio', 'Centaurea Cyanus Flower Water', '84012-19-1', 'Eaux Florales', 'France', 'Hydrolat de bleuet obtenu par distillation. Décongestionnant et apaisant, idéal pour le contour des yeux et les peaux réactives.', 'Décongestionnant, Apaisant, Tonifiant', 'Anti-poches, Rafraîchissant', NULL, 'Contour yeux, Toniques, Brumes', 'Hydrosoluble', 'Liquide limpide bleuté', 'COSMOS, BIO, ECOCERT', 'Peaux sensibles et réactives', 'Fleur', 'ACTIF', 'Non')
ON CONFLICT (code) DO NOTHING;

-- ================================================
-- PARFUMS (15 produits)
-- ================================================
INSERT INTO public.parfum_fr (code, nom_commercial, nom_latin, inci, cas_no, base, aspect, odeur, profil_olfactif, famille_olfactive, origin, description, application, certifications, food_grade, statut) VALUES
('PAR-001', 'Jasmin Absolu Grasse', 'Jasminum grandiflorum', 'Jasminum Grandiflorum Flower Extract', '8022-96-6', 'Alcool', 'Liquide brun ambré', 'Florale, riche, envoûtante', 'Notes florales blanches intenses, facettes animales et fruitées', 'Florale', 'France (Grasse)', 'Absolu de jasmin obtenu par extraction aux solvants volatils des fleurs de Jasminum grandiflorum cultivé à Grasse. Notes florales intenses et opulentes.', 'Parfumerie fine, Soins luxe', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-002', 'Bergamote Calabre', 'Citrus bergamia', 'Citrus Aurantium Bergamia Peel Oil', '8007-75-8', 'Naturel pur', 'Liquide jaune-vert', 'Hespéridée, fraîche, pétillante', 'Notes agrumes vives, facette aromatique légère, fond légèrement boisé', 'Hespéridée', 'Italie (Calabre)', 'Huile essentielle de bergamote pressée à froid des zestes de fruits cultivés en Calabre. Fraîcheur pétillante caractéristique.', 'Eaux de Cologne, Notes de tête, Thé', 'COSMOS, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-003', 'Santal Mysore', 'Santalum album', 'Santalum Album Oil', '8006-87-9', 'Naturel pur', 'Liquide visqueux jaune pâle', 'Boisée, lactée, crémeuse', 'Notes boisées douces, crémeuses et lactées avec fond animal subtil', 'Boisée', 'Inde (Mysore)', 'Huile essentielle de bois de santal de Mysore, la plus noble des qualités. Notes boisées crémeuses et lactées d''une finesse incomparable.', 'Parfumerie fine, Encens, Méditation', 'CITES Certified, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-004', 'Patchouli Indonésie', 'Pogostemon cablin', 'Pogostemon Cablin Oil', '8014-09-3', 'Naturel pur', 'Liquide brun foncé', 'Terreuse, boisée, camphrée', 'Notes terreuses profondes, boisées-camphrées, fond chocolaté', 'Boisée', 'Indonésie (Sulawesi)', 'Huile essentielle de patchouli distillée à partir des feuilles séchées. Notes terreuses et boisées profondes, pilier de la parfumerie orientale.', 'Parfumerie fine, Fonds orientaux', 'COSMOS, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-005', 'Ylang Ylang Extra', 'Cananga odorata', 'Cananga Odorata Flower Oil', '8006-81-3', 'Naturel pur', 'Liquide jaune pâle', 'Florale, exotique, jasminée', 'Notes florales exotiques, crémeuses, jasminées avec facette banane', 'Florale', 'Madagascar', 'Première fraction de distillation de l''ylang ylang, la plus riche et la plus florale. Notes exotiques intenses et crémeuses.', 'Parfumerie fine, Soins capillaires luxe', 'COSMOS, Fair Trade, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-006', 'Vétiver Haïti', 'Vetiveria zizanioides', 'Vetiveria Zizanoides Root Oil', '8016-96-4', 'Naturel pur', 'Liquide brun ambré visqueux', 'Terreuse, boisée, fumée', 'Notes terreuses-fumées, boisées sèches, fond ambré-cuiré', 'Boisée', 'Haïti', 'Huile essentielle de vétiver obtenue par distillation des racines. Notes terreuses et fumées d''une grande complexité aromatique.', 'Parfumerie masculine, Fonds boisés', 'Fair Trade, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-007', 'Rose Absolue Turquie', 'Rosa damascena', 'Rosa Damascena Flower Oil', '8007-01-0', 'Alcool', 'Liquide rouge orangé', 'Florale, miellée, épicée', 'Rose riche et profonde, facettes miel, épices et fruits rouges', 'Florale', 'Turquie (Isparta)', 'Absolu de rose de Damas de la vallée d''Isparta. Rose profonde et multifacettes aux notes miellées et légèrement épicées.', 'Parfumerie fine, Soins premium', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-008', 'Oud Royal', 'Aquilaria malaccensis', 'Aquilaria Malaccensis Oil', '94350-09-1', 'Naturel pur', 'Liquide brun foncé visqueux', 'Boisée, animale, fumée', 'Notes boisées animales intenses, cuir fumé, fond ambré-musqué', 'Orientale', 'Laos', 'Huile essentielle d''oud (bois d''agar) obtenue par distillation du bois résineux d''Aquilaria. L''ingrédient le plus précieux de la parfumerie orientale.', 'Parfumerie orientale, Collections prestige', 'CITES Certified, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-009', 'Iris Concret', 'Iris pallida', 'Iris Pallida Root Extract', '90045-89-9', 'Alcool', 'Solide cireux crème', 'Poudrée, violette, boisée', 'Notes poudrées élégantes, violette suave, fond boisé-terreux', 'Poudrée', 'Italie (Toscane)', 'Beurre d''iris obtenu après 3 ans de séchage des rhizomes et extraction. L''un des ingrédients les plus raffinés et coûteux de la parfumerie.', 'Parfumerie fine haute couture', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-010', 'Tonka Absolu', 'Dipteryx odorata', 'Dipteryx Odorata Bean Extract', '8046-22-8', 'Alcool', 'Liquide brun foncé', 'Amandée, vanillée, tabac', 'Notes amandées-vanillées, facettes foin, tabac blond, caramel', 'Orientale', 'Brésil', 'Absolu de fève tonka aux notes gourmandes et enveloppantes. Facettes amandées, vanillées et tabac blond d''une grande douceur.', 'Parfumerie orientale-gourmande, Fonds', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-011', 'Lavande Fine AOC', 'Lavandula angustifolia', 'Lavandula Angustifolia Oil', '8000-28-0', 'Naturel pur', 'Liquide jaune pâle', 'Aromatique, florale, camphrée', 'Notes aromatiques-florales, lavandulol, facette camphrée fine', 'Aromatique', 'France (Provence)', 'Huile essentielle de lavande fine de Haute-Provence AOC. Notes aromatiques élégantes et florales, pilier de la parfumerie française.', 'Parfumerie, Aromathérapie, Soins', 'AOC, COSMOS, IFRA Compliant', 'Non', 'ACTIF'),
('PAR-012', 'Encens Oliban Somalie', 'Boswellia carterii', 'Boswellia Carterii Oil', '8016-36-2', 'Naturel pur', 'Liquide jaune pâle', 'Résineuse, citronnée, épicée', 'Notes résineuses lumineuses, citronnées, poivrées, fond balsamique', 'Boisée', 'Somalie', 'Huile essentielle d''oliban obtenue par distillation de la résine de Boswellia carterii. Notes résineuses et spirituelles millénaires.', 'Parfumerie, Encens, Méditation', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-013', 'Tubéreuse Absolue', 'Polianthes tuberosa', 'Polianthes Tuberosa Extract', '8024-55-3', 'Alcool', 'Liquide brun ambré', 'Florale, crémeuse, entêtante', 'Notes florales blanches entêtantes, crémeuses, facettes cireuses', 'Florale', 'Inde (Tamil Nadu)', 'Absolu de tubéreuse aux notes florales blanches d''une intensité remarquable. Crémeuse, envoûtante et voluptueuse.', 'Parfumerie fine, Soliflores', 'IFRA Compliant', 'Non', 'ACTIF'),
('PAR-014', 'Mousse de Chêne Absolue', 'Evernia prunastri', 'Evernia Prunastri Extract', '90028-68-5', 'Alcool', 'Liquide vert brun', 'Boisée, terreuse, mousse', 'Notes de sous-bois, mousse verte, fond terreux-cuiré', 'Chyprée', 'France', 'Absolu de mousse de chêne, ingrédient emblématique des parfums chyprés. Notes de sous-bois et de mousse d''une grande élégance.', 'Parfumerie chyprée, Fougères', 'IFRA Compliant (dosage limité)', 'Non', 'ACTIF'),
('PAR-015', 'Ambre Gris Reconstitué', NULL, 'Ambergris Reconstitution', NULL, 'Reconstitution', 'Liquide ambré', 'Ambrée, marine, musquée', 'Notes ambrées marines, salées, fond musqué-animal élégant', 'Ambrée', 'France', 'Reconstitution d''ambre gris à partir d''ingrédients naturels et de synthèse. Reproduit les notes marines et ambrées de l''ambre gris naturel.', 'Parfumerie fine, Notes de fond', 'IFRA Compliant', 'Non', 'ACTIF')
ON CONFLICT (code) DO NOTHING;

-- ================================================
-- ARÔMES (15 produits)
-- ================================================
INSERT INTO public.aromes_fr (code, nom_commercial, inci, cas_no, base, aspect, dosage, profil_aromatique, origin, description, application, certifications, food_grade, gamme, statut) VALUES
('ARO-001', 'Vanille Madagascar Bourbon', 'Vanilla Planifolia Fruit Extract', '8024-06-4', 'Propylène glycol', 'Liquide brun foncé', '0.1% - 0.5%', 'Vanillée, sucrée, crémeuse, boisée', 'Madagascar', 'Extrait naturel de vanille bourbon de Madagascar. Notes vanillées riches et crémeuses avec des nuances boisées et caramélisées.', 'Boissons, Pâtisserie, Confiserie, Glaces', 'BIO, FEMA GRAS, EU Flavouring', 'Oui', 'Extraits Naturels', 'ACTIF'),
('ARO-002', 'Citron Sicile', 'Citrus Limon Peel Oil', '8008-56-8', 'Naturel pur', 'Liquide jaune clair', '0.05% - 0.3%', 'Citrique, zestée, fraîche, pétillante', 'Italie (Sicile)', 'Huile essentielle de citron de Sicile pressée à froid. Notes citriques vives et zestées d''une fraîcheur exceptionnelle.', 'Boissons, Pâtisserie, Confiserie', 'COSMOS, FEMA GRAS, EU Flavouring', 'Oui', 'Agrumes', 'ACTIF'),
('ARO-003', 'Fraise Naturelle', 'Natural Strawberry Flavouring', NULL, 'Propylène glycol', 'Liquide rouge clair', '0.1% - 0.5%', 'Fruitée, sucrée, fraise mûre', 'France', 'Arôme naturel de fraise élaboré à partir de fraises fraîches. Notes fruitées intenses de fraise mûre et sucrée.', 'Boissons, Yaourts, Confiserie, Glaces', 'EU Natural Flavouring, Halal', 'Oui', 'Fruits Rouges', 'ACTIF'),
('ARO-004', 'Menthe Poivrée Bio', 'Mentha Piperita Oil', '8006-90-4', 'Naturel pur', 'Liquide incolore à vert pâle', '0.02% - 0.2%', 'Mentholée, fraîche, vive, herbacée', 'États-Unis (Oregon)', 'Huile essentielle de menthe poivrée biologique. Notes mentholées puissantes et rafraîchissantes.', 'Confiserie, Boissons, Chewing-gum, Chocolat', 'COSMOS, BIO, FEMA GRAS', 'Oui', 'Herbes & Épices', 'ACTIF'),
('ARO-005', 'Orange Douce Brésil', 'Citrus Sinensis Peel Oil', '8028-48-6', 'Naturel pur', 'Liquide orange', '0.05% - 0.3%', 'Orange sucrée, fruitée, solaire', 'Brésil', 'Huile essentielle d''orange douce du Brésil. Notes d''orange sucrée et juteuse, chaude et solaire.', 'Boissons, Pâtisserie, Confiserie', 'FEMA GRAS, EU Flavouring, Kosher', 'Oui', 'Agrumes', 'ACTIF'),
('ARO-006', 'Café Arabica Colombie', 'Coffee Arabica Extract', '84650-00-0', 'Eau/Éthanol', 'Liquide brun foncé', '0.1% - 1%', 'Torréfié, chocolaté, noisette, amer', 'Colombie', 'Extrait de café arabica de Colombie, torréfaction moyenne. Notes torréfiées riches avec des nuances de chocolat et noisette.', 'Boissons, Glaces, Pâtisserie, Chocolat', 'Fair Trade, EU Flavouring', 'Oui', 'Extraits Naturels', 'ACTIF'),
('ARO-007', 'Caramel Beurre Salé', 'Natural Caramel Flavouring', NULL, 'Propylène glycol', 'Liquide brun ambré', '0.1% - 0.5%', 'Caramel, beurré, salé, gourmand', 'France (Bretagne)', 'Arôme naturel de caramel au beurre salé. Notes gourmandes de caramel beurré avec une pointe de sel de Guérande.', 'Pâtisserie, Glaces, Confiserie, Boissons lactées', 'EU Natural Flavouring', 'Oui', 'Gourmands', 'ACTIF'),
('ARO-008', 'Framboise Sauvage', 'Natural Raspberry Flavouring', NULL, 'Propylène glycol', 'Liquide rouge-violet', '0.1% - 0.4%', 'Framboise, acidulée, sucrée, végétale', 'France', 'Arôme naturel de framboise sauvage. Profil fruité intense avec un équilibre sucré-acidulé caractéristique.', 'Yaourts, Boissons, Confiserie, Pâtisserie', 'EU Natural Flavouring, Vegan', 'Oui', 'Fruits Rouges', 'ACTIF'),
('ARO-009', 'Chocolat Noir Ghana', 'Theobroma Cacao Extract', '95009-22-6', 'Eau/Éthanol', 'Liquide brun très foncé', '0.2% - 1%', 'Cacao amer, torréfié, fruité, boisé', 'Ghana', 'Extrait de cacao du Ghana, variété Forastero. Notes de cacao amer intenses avec des nuances fruitées et boisées.', 'Pâtisserie, Glaces, Boissons, Confiserie', 'Fair Trade, EU Flavouring, Kosher', 'Oui', 'Extraits Naturels', 'ACTIF'),
('ARO-010', 'Cannelle Ceylan Bio', 'Cinnamomum Zeylanicum Bark Oil', '8015-91-6', 'Naturel pur', 'Liquide brun jaune', '0.01% - 0.1%', 'Cannelle douce, épicée, chaude, sucrée', 'Sri Lanka', 'Huile essentielle de cannelle de Ceylan biologique (écorce). La plus fine des cannelles, douce et chaleureuse.', 'Pâtisserie, Boissons chaudes, Confiserie', 'COSMOS, BIO, FEMA GRAS', 'Oui', 'Herbes & Épices', 'ACTIF'),
('ARO-011', 'Passion Fruit Tropical', 'Natural Passion Fruit Flavouring', NULL, 'Propylène glycol', 'Liquide jaune-orange', '0.1% - 0.5%', 'Fruit de la passion, exotique, acidulé, musqué', 'Brésil', 'Arôme naturel de fruit de la passion. Notes exotiques intenses, acidulées et légèrement musquées.', 'Boissons, Yaourts, Sorbets, Confiserie', 'EU Natural Flavouring', 'Oui', 'Fruits Exotiques', 'ACTIF'),
('ARO-012', 'Noisette Piémont', 'Corylus Avellana Extract', '84012-21-5', 'Huile MCT', 'Liquide brun clair', '0.1% - 0.5%', 'Noisette grillée, pralinée, beurrée', 'Italie (Piémont)', 'Extrait naturel de noisette du Piémont IGP, torréfaction lente. Notes pralinées et beurrées d''une grande finesse.', 'Pâtisserie, Chocolat, Glaces, Café', 'IGP Piémont, EU Flavouring', 'Oui', 'Fruits à Coque', 'ACTIF'),
('ARO-013', 'Gingembre Frais Bio', 'Zingiber Officinale Root Oil', '8007-08-7', 'Naturel pur', 'Liquide jaune pâle', '0.02% - 0.15%', 'Épicé, frais, citronné, piquant', 'Inde (Kerala)', 'Huile essentielle de gingembre frais biologique. Notes épicées fraîches et citronnées avec une pointe piquante caractéristique.', 'Boissons, Confiserie, Sauces, Boulangerie', 'BIO, FEMA GRAS, EU Flavouring', 'Oui', 'Herbes & Épices', 'ACTIF'),
('ARO-014', 'Mangue Alphonso', 'Natural Mango Flavouring', NULL, 'Propylène glycol', 'Liquide jaune orangé', '0.1% - 0.5%', 'Mangue mûre, tropicale, sucrée, crémeuse', 'Inde', 'Arôme naturel de mangue Alphonso, la reine des mangues. Notes tropicales crémeuses et sucrées d''une intensité remarquable.', 'Boissons, Yaourts, Sorbets, Confiserie', 'EU Natural Flavouring, Halal', 'Oui', 'Fruits Exotiques', 'ACTIF'),
('ARO-015', 'Romarin Provence Bio', 'Rosmarinus Officinalis Leaf Oil', '8000-25-7', 'Naturel pur', 'Liquide incolore à jaune pâle', '0.01% - 0.1%', 'Herbacé, camphré, boisé, frais', 'France (Provence)', 'Huile essentielle de romarin de Provence biologique. Notes herbacées-camphrées typiques de la garrigue provençale.', 'Sauces, Marinades, Boulangerie, Boissons', 'COSMOS, BIO, AOC, FEMA GRAS', 'Oui', 'Herbes & Épices', 'ACTIF')
ON CONFLICT (code) DO NOTHING;

-- ================================================
-- DONNÉES DE PERFORMANCE PARFUM (pour PAR-001 et PAR-003)
-- ================================================
INSERT INTO public.parfum_performance (product_code, ordre, option_name, performance_value, performance_rating) VALUES
-- Jasmin Absolu Grasse (PAR-001)
('PAR-001', 1, 'Niveau d''utilisation', '1% - 5%', NULL),
('PAR-001', 2, 'Tenue', 'Excellente (8h+)', 5),
('PAR-001', 3, 'Diffusion', 'Forte', 4),
('PAR-001', 4, 'Substantivité', 'Élevée', 5),
('PAR-001', 5, 'Impact', 'Fort', 4),
('PAR-001', 6, 'Naturalité', '100% naturel', 5),
-- Santal Mysore (PAR-003)
('PAR-003', 1, 'Niveau d''utilisation', '3% - 15%', NULL),
('PAR-003', 2, 'Tenue', 'Exceptionnelle (12h+)', 5),
('PAR-003', 3, 'Diffusion', 'Moyenne', 3),
('PAR-003', 4, 'Substantivité', 'Très élevée', 5),
('PAR-003', 5, 'Impact', 'Modéré', 3),
('PAR-003', 6, 'Naturalité', '100% naturel', 5);

-- ================================================
-- DONNÉES DE STABILITÉ PARFUM (pour PAR-001 et PAR-003)
-- ================================================
INSERT INTO public.parfum_stabilite (product_code, ordre, base_name, ph_value, odeur_rating) VALUES
-- Jasmin Absolu Grasse (PAR-001)
('PAR-001', 1, 'Nettoyant acide', '2', 3),
('PAR-001', 2, 'Gel douche', '5.5', 4),
('PAR-001', 3, 'Shampooing', '6', 4),
('PAR-001', 4, 'Lait corporel', '6.5', 5),
('PAR-001', 5, 'Crème visage', '6', 5),
('PAR-001', 6, 'Bain moussant', '7', 4),
('PAR-001', 7, 'Savon liquide', '8', 3),
('PAR-001', 8, 'Lessive', '9', 2),
('PAR-001', 9, 'Nettoyant alcalin', '11', 1),
-- Santal Mysore (PAR-003)
('PAR-003', 1, 'Nettoyant acide', '2', 4),
('PAR-003', 2, 'Gel douche', '5.5', 5),
('PAR-003', 3, 'Shampooing', '6', 5),
('PAR-003', 4, 'Lait corporel', '6.5', 5),
('PAR-003', 5, 'Crème visage', '6', 5),
('PAR-003', 6, 'Bain moussant', '7', 5),
('PAR-003', 7, 'Savon liquide', '8', 4),
('PAR-003', 8, 'Lessive', '9', 4),
('PAR-003', 9, 'Nettoyant alcalin', '11', 3);

-- ================================================
-- CONTACT SUBMISSIONS DE DÉMONSTRATION (3 messages)
-- ================================================
INSERT INTO public.contact_submissions (first_name, last_name, email, company, phone, subject, message, status) VALUES
('Marie', 'Dupont', 'marie.dupont@beautelab.fr', 'Beauté Lab Paris', '+33 1 45 67 89 10', 'Demande de catalogue cosmétiques', 'Bonjour, nous sommes un laboratoire de formulation cosmétique basé à Paris. Nous aimerions recevoir votre catalogue complet d''ingrédients cosmétiques, notamment vos gammes d''actifs botaniques et d''huiles précieuses. Pourriez-vous également nous envoyer vos fiches techniques pour les références suivantes : Acide Hyaluronique Complex, Bakuchiol Natural et Peptide Matrixyl 3000 ? Merci d''avance.', 'new'),
('Thomas', 'Bernard', 'thomas.bernard@aromagroup.com', 'Aroma Group International', '+33 4 72 33 44 55', 'Partenariat arômes alimentaires', 'Bonjour, Aroma Group International recherche un fournisseur d''arômes naturels pour notre gamme de boissons fonctionnelles. Nous serions intéressés par vos extraits naturels (vanille, café, chocolat) ainsi que vos arômes de fruits exotiques. Serait-il possible d''organiser une visite de vos installations et d''obtenir des échantillons ? Cordialement.', 'read'),
('Elena', 'Rossi', 'elena.rossi@perfumeria.it', 'Perfumeria Milano', '+39 02 8847 5523', 'Sourcing matières premières parfumerie', 'Gentile team IES, siamo una casa di profumi boutique con sede a Milano. Cerchiamo forniture di assolute e oli essenziali di alta qualità, in particolare Jasmin Absolu, Rose Absolue e Oud Royal. Potreste inviarci campioni e listino prezzi? Grazie mille. / Chers équipe IES, nous sommes une maison de parfumerie boutique basée à Milan. Nous recherchons des approvisionnements en absolues et huiles essentielles de haute qualité.', 'new');

-- ================================================
-- SAMPLE REQUESTS DE DÉMONSTRATION (2 demandes)
-- ================================================
INSERT INTO public.sample_requests (contact_name, contact_email, contact_phone, company, message, status) VALUES
('Laurent Mercier', 'l.mercier@cosmeticsinnovation.fr', '+33 6 12 34 56 78', 'Cosmetics Innovation Lab', 'Nous développons une gamme de soins anti-âge premium et souhaitons tester vos actifs. Merci de nous envoyer des échantillons des références COS-002, COS-007 et COS-014.', 'pending'),
('Sarah Chen', 'sarah.chen@flavourhouse.co.uk', '+44 20 7946 0958', 'Flavour House UK', 'We are formulating a new range of natural beverages and would like to evaluate your flavour extracts. Could you please send samples of ARO-001, ARO-006 and ARO-011?', 'approved');
